package: sprog
version: '2.0.0-dev'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/

requires:
    redaxo: '^5.21'
    php: '^8.4'

filter:
    - Sprog\Filter\Format
    - Sprog\Filter\Limit
    - Sprog\Filter\Lower
    - Sprog\Filter\Markdown
    - Sprog\Filter\Raw
    - Sprog\Filter\Title
    - Sprog\Filter\Upper
    - Sprog\Filter\Words

page:
    title: 'translate:sprog'
    perm: sprog[]
    pjax: true
    icon: rex-icon rex-icon-language
    subpages:
        dashboard:
            title: 'translate:sprog_dashboard_subpage'
        inbox:
            title: 'translate:sprog_inbox_subpage'
        create:
            title: 'translate:sprog_create_subpage'
            hidden: true
        glossary:
            title: 'translate:sprog_glossary_subpage'
            perm: admin[]
        wildcard:
            title: 'translate:wildcard'
            perm: sprog[wildcard]
        abbreviation:
            title: 'translate:abbreviations'
            perm: sprog[abbreviation]
        copy:
            title: 'translate:copy_content'
            perm: admin[]
            subpages:
                structure_content:
                    title: 'translate:copy_structure_content'
                structure_metadata:
                    title: 'translate:copy_structure_metadata'
        artefact:
            title: 'translate:artefact'
            perm: admin[]
            pjax: false
            subpages:
                import:
                    title: 'translate:import'
                export:
                    title: 'translate:export'
#                cleanup:
#                    title: 'translate:cleanup'
        migration:
            title: 'translate:sprog_migration_subpage'
            perm: admin[]
        settings:
            title: 'translate:settings'
            perm: admin[]
            subPath: pages/settings.php
        help:
            title: 'translate:help'
            subPath: README.md
            perm: admin[]
            itemClass: pull-right


pages:
    sprog.copy.structure_content_popup:
        title: 'translate:copy_structure_content_popup'
        perm: admin[]
        main: true
        popup: true
        hidden: true
    sprog.copy.structure_content_generate:
        title: 'translate:copy_structure_content_generate'
        perm: admin[]
        main: true
        hasLayout: false
        hidden: true
    sprog.copy.structure_metadata_popup:
        title: 'translate:copy_structure_metadata_popup'
        perm: admin[]
        main: true
        popup: true
        hidden: true
    sprog.copy.structure_metadata_generate:
        title: 'translate:copy_structure_metadata_generate'
        perm: admin[]
        main: true
        hasLayout: false
        hidden: true

default_config:
    wildcard_open_tag: '{{ '
    wildcard_close_tag: ' }}'
    chunk_size_articles: 4
    workflow_dev_self_approve: false
