package: sprog
version: '1.1.0'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/
docspage: https://github.com/tbaddade/redaxo_sprog/edit/master/README.md

requires:
    redaxo: '^5.5'

filter:
    - Sprog\Filter\Format
    - Sprog\Filter\Limit
    - Sprog\Filter\Lower
    - Sprog\Filter\Markdown
    - Sprog\Filter\Raw
    - Sprog\Filter\Title
    - Sprog\Filter\Upper
    - Sprog\Filter\Words

page:
    title: 'translate:sprog'
    perm: sprog[]
    pjax: true
    icon: rex-icon rex-icon-language
    subpages:
        wildcard:
            title: 'translate:wildcard'
        copy:
            title: 'translate:copy_content'
            perm: admin[]
            subpages:
                structure_content:
                    title: 'translate:copy_structure_content'
                structure_metadata:
                    title: 'translate:copy_structure_metadata'
        settings:
            title: 'translate:settings'
            perm: admin[]
        docs: 
            title: 'translate:docs'
            icon: rex-icon fa-info-circle
            itemclass: pull-right


pages:
    sprog.copy.structure_content_popup:
        title: 'translate:copy_structure_content_popup'
        main: true
        popup: true
        hidden: true
    sprog.copy.structure_content_generate:
        title: 'translate:copy_structure_content_generate'
        main: true
        hasLayout: false
        hidden: true
    sprog.copy.structure_metadata_popup:
        title: 'translate:copy_structure_metadata_popup'
        main: true
        popup: true
        hidden: true
    sprog.copy.structure_metadata_generate:
        title: 'translate:copy_structure_metadata_generate'
        main: true
        hasLayout: false
        hidden: true
